version: '2'
services:
    farming-app:
        image: farming
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://farming-postgresql:5432/farming
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=farming-elasticsearch:9300
        ports:
            - 8084:8084
    farming-postgresql:
        extends:
            file: postgresql.yml
            service: farming-postgresql
    farming-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: farming-elasticsearch
